#!/usr/bin/env python3
"""Plot the empirical Th-232 threshold curve after adding the 209-keV anchor.

This is a diagnostic view of the direct threshold points. It uses a shape-
preserving PCHIP interpolation only to connect neighboring measured anchors;
it does not select or apply a parametric functional fit. Error bars are read
from the event-level bootstrap output generated by
``fit_th232_threshold_curves_with_uncertainty.py``.
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import matplotlib
import numpy as np
from scipy.interpolate import PchipInterpolator

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))

from scripts.plot_th232_revised_pb_threshold_curves import (  # noqa: E402
    PB_ANCHORS,
    RETENTION_ONLY_ANCHOR,
    SCORE_GRID,
    TARGET_GAINS_PCT,
    relative,
    write_csv,
)

DEFAULT_INPUT_DIR = (
    PROJECT_ROOT
    / "outputs/experiments/th232_revised_pb_threshold_curves_20260824_with_209_300_409_uncertainty"
)
DEFAULT_OUTPUT_DIR = (
    PROJECT_ROOT
    / "outputs/experiments/th232_revised_pb_threshold_curves_20260824_with_209_300_409_empirical"
)


def read_csv_rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as stream:
        return list(csv.DictReader(stream))


def as_float(row: dict[str, str], field: str) -> float:
    return float(row[field])


def build_empirical_curves(
    point_rows: list[dict[str, str]],
) -> tuple[dict[int, tuple[np.ndarray, np.ndarray]], dict[int, list[dict[str, str]]]]:
    """Return dense PCHIP curves and sorted direct-point rows by target."""

    curves: dict[int, tuple[np.ndarray, np.ndarray]] = {}
    rows_by_target: dict[int, list[dict[str, str]]] = {}
    expected_energies = {spec.reference_kev for spec in PB_ANCHORS}

    for target_pct in TARGET_GAINS_PCT:
        rows = [
            row
            for row in point_rows
            if int(round(as_float(row, "target_pb_gain_percent"))) == target_pct
        ]
        rows.sort(key=lambda row: as_float(row, "observed_centroid_kev"))
        if len(rows) != len(PB_ANCHORS):
            raise ValueError(
                f"Target +{target_pct}% has {len(rows)} rows; expected {len(PB_ANCHORS)}"
            )
        reference_energies = {as_float(row, "reference_energy_kev") for row in rows}
        if reference_energies != expected_energies:
            raise ValueError(
                f"Target +{target_pct}% does not contain the current PB_ANCHORS set"
            )

        energies = np.asarray(
            [as_float(row, "observed_centroid_kev") for row in rows], dtype=np.float64
        )
        thresholds = np.asarray(
            [as_float(row, "target_threshold") for row in rows], dtype=np.float64
        )
        if not np.all(np.isfinite(energies)) or not np.all(np.isfinite(thresholds)):
            raise ValueError(f"Non-finite empirical point for target +{target_pct}%")
        if np.any(np.diff(energies) <= 0.0):
            raise ValueError(f"Observed anchor energies are not strictly increasing for +{target_pct}%")

        interpolator = PchipInterpolator(energies, thresholds)
        dense_energy = np.arange(
            float(energies[0]), float(energies[-1]) + 0.5, 1.0
        )
        curves[target_pct] = (
            dense_energy,
            np.clip(np.asarray(interpolator(dense_energy), dtype=np.float64), 0.0, 1.0),
        )
        rows_by_target[target_pct] = rows

    return curves, rows_by_target


def read_retention_curve(path: Path) -> tuple[np.ndarray, np.ndarray]:
    rows = read_csv_rows(path)
    thresholds = np.asarray([as_float(row, "score_threshold") for row in rows])
    retention = np.asarray(
        [as_float(row, "th232_2614_roi_retention") for row in rows]
    )
    if thresholds.size != SCORE_GRID.size or not np.allclose(thresholds, SCORE_GRID):
        raise ValueError("Retention diagnostic does not use the expected score grid")
    return thresholds, retention


def plot_empirical_curves(
    output_path: Path,
    curves: dict[int, tuple[np.ndarray, np.ndarray]],
    rows_by_target: dict[int, list[dict[str, str]]],
    retention_thresholds: np.ndarray,
    retention: np.ndarray,
) -> None:
    colors = dict(
        zip(
            TARGET_GAINS_PCT,
            plt.cm.viridis(np.linspace(0.1, 0.9, len(TARGET_GAINS_PCT))),
        )
    )
    figure, axes = plt.subplots(
        2,
        1,
        figsize=(15, 10),
        gridspec_kw={"height_ratios": (1.25, 1.0)},
        constrained_layout=True,
    )
    threshold_axis, retention_axis = axes

    for target_pct in TARGET_GAINS_PCT:
        color = colors[target_pct]
        dense_energy, dense_threshold = curves[target_pct]
        rows = rows_by_target[target_pct]
        energies = np.asarray(
            [as_float(row, "observed_centroid_kev") for row in rows], dtype=np.float64
        )
        thresholds = np.asarray(
            [as_float(row, "target_threshold") for row in rows], dtype=np.float64
        )
        lower = np.asarray(
            [as_float(row, "bootstrap_ci_low") for row in rows], dtype=np.float64
        )
        upper = np.asarray(
            [as_float(row, "bootstrap_ci_high") for row in rows], dtype=np.float64
        )
        threshold_axis.plot(
            dense_energy,
            dense_threshold,
            color=color,
            linewidth=2.1,
            label=f"+{target_pct}% P/B target",
        )
        threshold_axis.errorbar(
            energies,
            thresholds,
            yerr=np.vstack(
                (
                    np.maximum(thresholds - lower, 0.0),
                    np.maximum(upper - thresholds, 0.0),
                )
            ),
            fmt="o",
            markersize=4.5,
            color=color,
            ecolor=color,
            elinewidth=0.9,
            capsize=2.5,
            alpha=0.8,
            markeredgecolor="black",
            markeredgewidth=0.35,
            zorder=3,
        )

    threshold_axis.axvspan(190.0, 230.0, color="tab:orange", alpha=0.08)
    threshold_axis.text(
        192.0,
        0.97,
        "<230 keV",
        color="tab:orange",
        fontsize=9,
        va="top",
    )
    threshold_axis.axvline(
        RETENTION_ONLY_ANCHOR.reference_kev,
        color="0.55",
        linestyle=":",
        linewidth=1.0,
    )
    threshold_axis.axvline(1460.438, color="0.35", linestyle="--", linewidth=1.0)
    threshold_axis.text(
        1460.438,
        0.97,
        "P/B domain limit",
        rotation=90,
        ha="right",
        va="top",
        fontsize=9,
        color="0.25",
    )
    threshold_axis.set_xlim(190.0, 1500.0)
    threshold_axis.set_ylim(0.0, 1.0)
    threshold_axis.set_ylabel("DS-CNN score threshold T(E)")
    threshold_axis.set_title(
        "Empirical Th-232 energy-dependent thresholds after adding the 209-keV anchor",
        fontweight="bold",
    )
    threshold_axis.text(
        0.01,
        0.02,
        "Points: direct anchor thresholds with 95% event-bootstrap intervals; lines: PCHIP interpolation only",
        transform=threshold_axis.transAxes,
        fontsize=9,
        color="0.25",
    )
    threshold_axis.grid(alpha=0.25)
    threshold_axis.legend(ncol=2, fontsize=9, loc="upper right")

    retention_axis.plot(
        retention_thresholds,
        retention,
        color="black",
        linewidth=1.8,
        label="2614.5-keV ROI retention",
    )
    for target_pct in TARGET_GAINS_PCT:
        color = colors[target_pct]
        rows = rows_by_target[target_pct]
        boundary = max(rows, key=lambda row: as_float(row, "observed_centroid_kev"))
        threshold = as_float(boundary, "target_threshold")
        retention_value = float(
            retention[np.argmin(np.abs(retention_thresholds - threshold))]
        )
        retention_axis.axvline(threshold, color=color, linestyle="--", linewidth=0.9)
        retention_axis.scatter([threshold], [retention_value], color=color, s=30, zorder=3)
        retention_axis.annotate(
            f"+{target_pct}%",
            (threshold, retention_value),
            xytext=(4, 4),
            textcoords="offset points",
            fontsize=8,
            color=color,
        )
    retention_axis.set_xlim(0.0, 0.90)
    retention_axis.set_ylim(0.0, 1.05)
    retention_axis.set_xlabel("Score threshold")
    retention_axis.set_ylabel("2614-keV ROI retention")
    retention_axis.set_title(
        "2614.5-keV retention-only diagnostic (not used for P/B fitting)",
        fontweight="bold",
    )
    retention_axis.grid(alpha=0.25)
    retention_axis.legend(fontsize=9, loc="upper right")

    figure.savefig(output_path, dpi=200)
    plt.close(figure)


def make_report(
    input_dir: Path,
    output_dir: Path,
    rows_by_target: dict[int, list[dict[str, str]]],
) -> str:
    first_target_rows = rows_by_target[TARGET_GAINS_PCT[0]]
    first_anchor = min(
        first_target_rows,
        key=lambda row: as_float(row, "observed_centroid_kev"),
    )
    last_anchor = max(
        first_target_rows,
        key=lambda row: as_float(row, "observed_centroid_kev"),
    )
    lines = [
        "# Empirical Th-232 energy-dependent threshold curve",
        "",
        "This diagnostic adds the 209.253-keV Ac-228 line to the P/B anchor set after the observed suppression of the region below 230 keV. The plotted lines are shape-preserving PCHIP interpolation between direct anchor thresholds; no exponential, polynomial, or other parametric function has been selected.",
        "",
        f"- Input bootstrap points: `{relative(input_dir / 'th232_threshold_anchor_uncertainty.csv')}`",
        f"- Plot: `{relative(output_dir / 'th232_empirical_threshold_curves.png')}`",
        f"- Interpolated curve table: `{relative(output_dir / 'th232_empirical_threshold_curves_1kev.csv')}`",
        f"- P/B domain: {as_float(first_anchor, 'observed_centroid_kev'):.3f}--{as_float(last_anchor, 'observed_centroid_kev'):.3f} keV observed centroids",
        "- 2614.5 keV remains retention-only; it is not used for P/B background estimation or threshold fitting.",
        "- Error bars are 95% percentile intervals from 200 event-level bootstrap replicates with fixed fitted peak windows; calibration and sideband-model systematics are not included.",
        "",
        "## Anchor diagnostics",
        "",
        "| Reference (keV) | Observed centroid (keV) | Sideband | Base P/B |",
        "|---:|---:|:---|---:|",
    ]
    seen: set[float] = set()
    for row in sorted(
        first_target_rows,
        key=lambda item: as_float(item, "observed_centroid_kev"),
    ):
        reference = as_float(row, "reference_energy_kev")
        if reference in seen:
            continue
        seen.add(reference)
        lines.append(
            f"| {reference:.3f} | {as_float(row, 'observed_centroid_kev'):.3f} | {row['sideband_mode']} | {as_float(row, 'base_peak_to_background'):.4f} |"
        )
    lines.extend(
        [
            "",
            "The 209-keV point is a low-P/B anchor and therefore carries more sideband-model risk than the stronger isolated lines. It is included to constrain the low-energy operating curve, but should be treated as a diagnostic anchor pending a dedicated background audit.",
            "",
            "These are optimization diagnostics on the historical Th-232 score cache, not external validation.",
            "",
        ]
    )
    return "\n".join(lines)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input-dir", type=Path, default=DEFAULT_INPUT_DIR)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    return parser


def main() -> int:
    args = build_parser().parse_args()
    input_dir = args.input_dir.resolve()
    output_dir = args.output_dir.resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    point_rows = read_csv_rows(input_dir / "th232_threshold_anchor_uncertainty.csv")
    curves, rows_by_target = build_empirical_curves(point_rows)
    retention_thresholds, retention = read_retention_curve(
        input_dir / "th232_2614_retention_diagnostic.csv"
    )

    curve_rows: list[dict[str, Any]] = []
    for target_pct in TARGET_GAINS_PCT:
        dense_energy, dense_threshold = curves[target_pct]
        for energy_kev, threshold in zip(dense_energy, dense_threshold):
            curve_rows.append(
                {
                    "energy_kev": float(energy_kev),
                    "target_pb_gain_percent": float(target_pct),
                    "threshold": float(threshold),
                }
            )
    curve_csv = output_dir / "th232_empirical_threshold_curves_1kev.csv"
    plot_path = output_dir / "th232_empirical_threshold_curves.png"
    report_path = output_dir / "report.md"
    report_json_path = output_dir / "th232_empirical_threshold_curves_report.json"
    write_csv(curve_csv, curve_rows)
    plot_empirical_curves(
        plot_path,
        curves,
        rows_by_target,
        retention_thresholds,
        retention,
    )

    report = {
        "schema_version": 1,
        "status": "TH232_EMPIRICAL_THRESHOLD_CURVES_COMPLETE",
        "created_utc": datetime.now(timezone.utc).isoformat(),
        "input_dir": relative(input_dir),
        "target_gains_percent": list(TARGET_GAINS_PCT),
        "pb_anchor_specs": [spec.__dict__ for spec in PB_ANCHORS],
        "retention_only_anchor": RETENTION_ONLY_ANCHOR.__dict__,
        "interpolation": {
            "method": "PCHIP",
            "parametric_fit_selected": False,
            "purpose": "shape-preserving visualization between measured anchor thresholds",
        },
        "point_rows": point_rows,
        "artifacts": {
            "plot": relative(plot_path),
            "curve_csv": relative(curve_csv),
            "report": relative(report_path),
        },
        "claim_boundary": "Direct historical Th-232 optimization diagnostics with event-bootstrap statistical intervals; not external validation and not a finalized deployment threshold function.",
    }
    report_json_path.write_text(
        json.dumps(report, indent=2, sort_keys=True, allow_nan=True) + "\n",
        encoding="utf-8",
    )
    report_path.write_text(
        make_report(input_dir, output_dir, rows_by_target),
        encoding="utf-8",
    )
    print(
        json.dumps(
            {
                "status": report["status"],
                "output_dir": str(output_dir),
                "artifacts": [
                    plot_path.name,
                    curve_csv.name,
                    report_path.name,
                    report_json_path.name,
                ],
            },
            indent=2,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
