#!/usr/bin/env python3
"""Train a provisional O2-style charge/current late-fusion classifier.

This trainer consumes the index-only, file-partitioned pair manifests generated by
``build_energy_matched_labels.py``.  It never materializes a second waveform data
set: each event row is read from its source HDF5 file, converted into two physical
representations, and passed to a small two-branch 1-D CNN.

The implementation is deliberately explicit because this repository did not contain
a canonical O2 model definition.  The frozen representation is:

* median baseline from samples 0:1000;
* baseline-subtracted charge, causally averaged over 10 samples;
* charge window sampled from t10 - 250 through t10 + 499 (750 samples), where t10
  is the interpolated 10%-of-pulse crossing of the smoothed charge;
* current = d(charge)/dt using a 4 ns sample period;
* current window from current-peak - 125 through current-peak + 125 (251 samples),
  with the peak searched in samples 1100:1500;
* both branches normalized by the positive frozen ``shaped_energy_unit``.

Only train and validation partitions are loaded.  The test partition is intentionally
left untouched for a later locked evaluation.  Validation AUROC is an internal,
model-selection diagnostic, not an unbiased physics-performance estimate: positive
and negative classes originate from different isotope sources and the exploratory
manifest retains non-PASS QC files.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import random
from collections import defaultdict
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable

import h5py
import numpy as np
import torch
from sklearn.metrics import average_precision_score, roc_auc_score
from torch import Tensor, nn
from torch.utils.data import DataLoader, TensorDataset

PROJECT_ROOT = Path(__file__).resolve().parents[1]
PARTITIONS = ("train", "validation")
SAMPLE_PERIOD_NS = 4.0
BASELINE_STOP = 1000
MOVING_AVERAGE_WIDTH = 10
T10_SEARCH_START = 1000
T10_SEARCH_STOP = 2000
CURRENT_SEARCH_START = 1100
CURRENT_SEARCH_STOP = 1500
CHARGE_PRE_SAMPLES = 250
CHARGE_POST_SAMPLES = 500
CHARGE_LENGTH = CHARGE_PRE_SAMPLES + CHARGE_POST_SAMPLES
CURRENT_HALF_WIDTH = 125
CURRENT_LENGTH = 2 * CURRENT_HALF_WIDTH + 1
FEATURE_CHUNK_SIZE = 512

ARCHITECTURE = {
    "name": "O2_style_charge_current_late_fusion",
    "charge_branch": {
        "input_length": CHARGE_LENGTH,
        "conv_channels": [16, 32, 64],
        "kernels": [9, 9, 7],
        "pooling": "max_pool_2_after_each_convolution",
        "embedding_dim": 64,
    },
    "current_branch": {
        "input_length": CURRENT_LENGTH,
        "conv_channels": [16, 32, 64],
        "kernels": [7, 7, 5],
        "pooling": "max_pool_2_after_each_convolution",
        "embedding_dim": 64,
    },
    "fusion": {
        "input_dim": 128,
        "hidden_dim": 64,
        "dropout": 0.20,
        "output": "one logit",
    },
}
TRAINING_CONFIG = {
    "optimizer": "AdamW",
    "learning_rate": 1.0e-3,
    "weight_decay": 1.0e-4,
    "batch_size": 512,
    "max_epochs": 20,
    "early_stopping_patience": 5,
    "early_stopping_metric": "validation_weighted_auroc",
    "seed": 20260810,
}


@dataclass(frozen=True)
class EventReference:
    hdf5_path: str
    row: int
    label: int
    weight: float
    peak_id: str


@dataclass
class PartitionData:
    charge: np.ndarray
    current: np.ndarray
    labels: np.ndarray
    weights: np.ndarray
    peak_ids: np.ndarray
    t10_fallback_count: int


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def sha256_file(path: Path, chunk_size: int = 8 * 1024 * 1024) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        while chunk := stream.read(chunk_size):
            digest.update(chunk)
    return digest.hexdigest()


def causal_moving_average(values: np.ndarray, width: int) -> np.ndarray:
    """Apply a causal moving average without shifting the waveform."""
    cumulative = np.cumsum(values, axis=1, dtype=np.float32)
    result = np.empty_like(values, dtype=np.float32)
    prefix_lengths = np.arange(1, width, dtype=np.float32)
    if width > 1:
        result[:, : width - 1] = cumulative[:, : width - 1] / prefix_lengths[None, :]
    previous = np.concatenate(
        (
            np.zeros((values.shape[0], 1), dtype=np.float32),
            cumulative[:, :-width],
        ),
        axis=1,
    )
    result[:, width - 1 :] = (
        cumulative[:, width - 1 :] - previous
    ) / float(width)
    return result


def interpolated_t10(smoothed_charge: np.ndarray) -> tuple[np.ndarray, int]:
    """Return fractional t10 crossings and the count of deterministic fallbacks.

    The pulse peak is selected from the same smoothed, baseline-subtracted charge
    representation used for the crossing.  The crossing is linearly interpolated
    between adjacent samples, making the subsequent window alignment deterministic.
    A selected low-energy/no-pulse candidate can have a non-positive smoothed peak;
    in that case the charge window is deterministically padded from sample 1000 and
    the fallback is recorded in run metadata rather than silently dropping the event.
    """
    peak_indices = (
        np.argmax(
            smoothed_charge[:, T10_SEARCH_START:T10_SEARCH_STOP],
            axis=1,
        )
        + T10_SEARCH_START
    )
    peak_values = smoothed_charge[
        np.arange(smoothed_charge.shape[0]), peak_indices
    ]
    valid = peak_values > 0.0
    fallback_count = int(np.count_nonzero(~valid))
    positions = np.full(
        smoothed_charge.shape[0], float(T10_SEARCH_START), dtype=np.float32
    )
    if not np.any(valid):
        return positions, fallback_count
    search = smoothed_charge[:, T10_SEARCH_START:T10_SEARCH_STOP]
    search_offsets = np.arange(search.shape[1], dtype=np.int64)
    thresholds = 0.1 * peak_values
    before_peak = search_offsets[None, :] <= (
        peak_indices - T10_SEARCH_START
    )[:, None]
    crossed = (search >= thresholds[:, None]) & before_peak & valid[:, None]
    if np.any(valid & ~np.any(crossed, axis=1)):
        index = int(np.flatnonzero(valid & ~np.any(crossed, axis=1))[0])
        raise ValueError(
            "No t10 crossing found in the physical search interval; "
            f"event batch index={index}, peak_index={peak_indices[index]}"
        )
    crossing = np.argmax(crossed, axis=1) + T10_SEARCH_START
    interpolated = valid & (crossing > T10_SEARCH_START)
    indices = np.flatnonzero(interpolated)
    if indices.size:
        crossing_indices = crossing[indices]
        before = smoothed_charge[indices, crossing_indices - 1]
        after = smoothed_charge[indices, crossing_indices]
        denominator = after - before
        fraction = np.divide(
            thresholds[indices] - before,
            denominator,
            out=np.zeros_like(before, dtype=np.float32),
            where=denominator != 0.0,
        )
        positions[indices] = (
            crossing_indices.astype(np.float32)
            - 1.0
            + np.clip(fraction, 0.0, 1.0)
        )
    return positions, fallback_count


def extract_o2_features(
    waveforms: np.ndarray,
    shaped_energy_unit: np.ndarray,
) -> tuple[np.ndarray, np.ndarray, int]:
    """Extract normalized charge and current branch inputs for one batch."""
    waveforms = np.asarray(waveforms, dtype=np.float32)
    shaped_energy_unit = np.asarray(shaped_energy_unit, dtype=np.float32)
    if waveforms.ndim != 2 or waveforms.shape[1] != 4500:
        raise ValueError(f"Expected (N, 4500) waveforms, got {waveforms.shape}")
    if not np.all(np.isfinite(waveforms)):
        raise ValueError("Non-finite waveform sample encountered")
    if not np.all(np.isfinite(shaped_energy_unit)) or np.any(shaped_energy_unit <= 0.0):
        raise ValueError("Frozen shaped_energy_unit must be finite and positive")

    baseline = np.median(waveforms[:, :BASELINE_STOP], axis=1).astype(np.float32)
    charge = baseline[:, None] - waveforms
    smoothed_charge = causal_moving_average(charge, MOVING_AVERAGE_WIDTH)
    t10, t10_fallback_count = interpolated_t10(smoothed_charge)

    charge_offsets = np.arange(-CHARGE_PRE_SAMPLES, CHARGE_POST_SAMPLES, dtype=np.float32)
    sample_positions = t10[:, None] + charge_offsets[None, :]
    if sample_positions.min() < 0.0 or sample_positions.max() > waveforms.shape[1] - 1:
        raise ValueError("Charge window out of bounds")
    left_indices = np.floor(sample_positions).astype(np.int64)
    right_indices = np.minimum(left_indices + 1, waveforms.shape[1] - 1)
    fraction = sample_positions - left_indices
    event_indices = np.arange(waveforms.shape[0])[:, None]
    left_values = smoothed_charge[event_indices, left_indices]
    right_values = smoothed_charge[event_indices, right_indices]
    charge_branch = (
        left_values + fraction * (right_values - left_values)
    ).astype(np.float32)

    current = np.gradient(charge, SAMPLE_PERIOD_NS, axis=1).astype(np.float32)
    current_peak = (
        np.argmax(
            current[:, CURRENT_SEARCH_START:CURRENT_SEARCH_STOP],
            axis=1,
        )
        + CURRENT_SEARCH_START
    )
    current_offsets = np.arange(
        -CURRENT_HALF_WIDTH,
        CURRENT_HALF_WIDTH + 1,
        dtype=np.int64,
    )
    current_indices = current_peak[:, None] + current_offsets[None, :]
    if current_indices.min() < 0 or current_indices.max() >= waveforms.shape[1]:
        raise ValueError("Current window out of bounds")
    current_branch = current[
        np.arange(waveforms.shape[0])[:, None],
        current_indices,
    ].astype(np.float32)

    # The positive shaped-energy quantity is the frozen trapezoid normalization.
    # Do not use abs(): a non-positive value indicates a reconstruction failure.
    scale = shaped_energy_unit[:, None]
    charge_branch /= scale
    current_branch /= scale
    if not np.all(np.isfinite(charge_branch)) or not np.all(np.isfinite(current_branch)):
        raise ValueError("Non-finite O2 feature generated")
    return charge_branch, current_branch, t10_fallback_count


def read_partition_events(
    csv_path: Path,
    max_events: int | None = None,
) -> list[EventReference]:
    """Expand each positive/negative matched pair into event-level records."""
    records: list[EventReference] = []
    with csv_path.open(newline="", encoding="utf-8") as stream:
        for pair in csv.DictReader(stream):
            records.append(
                EventReference(
                    hdf5_path=pair["positive_hdf5"],
                    row=int(pair["positive_row"]),
                    label=int(pair["positive_label"]),
                    weight=float(pair["source_weight"]),
                    peak_id=pair["peak_id"],
                )
            )
            records.append(
                EventReference(
                    hdf5_path=pair["negative_hdf5"],
                    row=int(pair["negative_row"]),
                    label=int(pair["negative_label"]),
                    weight=float(pair["source_weight"]),
                    peak_id=pair["peak_id"],
                )
            )
            if max_events is not None and len(records) >= max_events:
                break
    if not records:
        raise ValueError(f"No events found in {csv_path}")
    if max_events is not None:
        records = records[:max_events]
    labels = {record.label for record in records}
    if labels != {0, 1}:
        raise ValueError(f"Expected both labels in {csv_path}; found {labels}")
    return records


def build_partition_features(
    csv_path: Path,
    max_events: int | None = None,
    event_store_dir: Path | None = None,
) -> PartitionData:
    """Read only referenced HDF5 rows and construct the event-level features."""
    records = read_partition_events(csv_path, max_events=max_events)
    if event_store_dir is not None:
        return build_partition_features_from_event_store(
            csv_path,
            records,
            event_store_dir,
        )

    charge = np.empty((len(records), CHARGE_LENGTH), dtype=np.float32)
    current = np.empty((len(records), CURRENT_LENGTH), dtype=np.float32)
    labels = np.asarray([record.label for record in records], dtype=np.float32)
    weights = np.asarray([record.weight for record in records], dtype=np.float32)
    peak_ids = np.asarray([record.peak_id for record in records], dtype="U64")
    t10_fallback_count = 0

    grouped: dict[str, list[tuple[int, int]]] = defaultdict(list)
    for destination, record in enumerate(records):
        grouped[record.hdf5_path].append((destination, record.row))

    for relative_path, references in sorted(grouped.items()):
        hdf5_path = PROJECT_ROOT / relative_path
        if not hdf5_path.is_file():
            raise FileNotFoundError(hdf5_path)
        with h5py.File(hdf5_path, "r") as handle:
            waveform_dataset = handle["waveform"]
            energy_dataset = handle["shaped_energy_unit"]
            for start in range(0, len(references), FEATURE_CHUNK_SIZE):
                chunk = references[start : start + FEATURE_CHUNK_SIZE]
                destinations = np.asarray([item[0] for item in chunk], dtype=np.int64)
                rows = np.asarray([item[1] for item in chunk], dtype=np.int64)
                order = np.argsort(rows)
                sorted_rows = rows[order]
                waveforms = waveform_dataset[sorted_rows]
                shaped = energy_dataset[sorted_rows]
                (
                    chunk_charge,
                    chunk_current,
                    chunk_fallback_count,
                ) = extract_o2_features(waveforms, shaped)
                charge[destinations[order]] = chunk_charge
                current[destinations[order]] = chunk_current
                t10_fallback_count += chunk_fallback_count

    return PartitionData(
        charge,
        current,
        labels,
        weights,
        peak_ids,
        t10_fallback_count,
    )


def build_partition_features_from_event_store(
    csv_path: Path,
    records: list[EventReference],
    event_store_dir: Path,
) -> PartitionData:
    """Build features from a consolidated partition store instead of source files."""
    partition = csv_path.stem.removeprefix("label_pairs_")
    store_path = event_store_dir / f"{partition}_events.h5"
    lookup_path = event_store_dir / f"event_lookup_{partition}.csv"
    for path in (store_path, lookup_path):
        if not path.is_file():
            raise FileNotFoundError(path)
    required_keys = {(record.hdf5_path, record.row) for record in records}
    lookup: dict[tuple[str, int], int] = {}
    with lookup_path.open(newline="", encoding="utf-8") as stream:
        for row in csv.DictReader(stream):
            key = (row["source_hdf5"], int(row["source_row"]))
            if key in required_keys:
                lookup[key] = int(row["store_index"])
    missing = required_keys - set(lookup)
    if missing:
        example = next(iter(missing))
        raise KeyError(
            f"Event store is missing {len(missing)} referenced events; example={example}"
        )

    charge = np.empty((len(records), CHARGE_LENGTH), dtype=np.float32)
    current = np.empty((len(records), CURRENT_LENGTH), dtype=np.float32)
    labels = np.asarray([record.label for record in records], dtype=np.float32)
    weights = np.asarray([record.weight for record in records], dtype=np.float32)
    peak_ids = np.asarray([record.peak_id for record in records], dtype="U64")
    store_rows = np.asarray(
        [lookup[(record.hdf5_path, record.row)] for record in records],
        dtype=np.int64,
    )
    order = np.argsort(store_rows)
    sorted_rows = store_rows[order]
    if np.unique(sorted_rows).size != sorted_rows.size:
        raise ValueError("Pair manifest reuses an event within a partition")
    t10_fallback_count = 0
    with h5py.File(store_path, "r") as handle:
        if str(handle.attrs["partition"]) != partition:
            raise ValueError(f"Event-store partition mismatch: {store_path}")
        waveform_dataset = handle["waveform"]
        energy_dataset = handle["shaped_energy_unit"]
        selection_density = sorted_rows.size / waveform_dataset.shape[0]
        preload_store = selection_density >= 0.20
        waveform_values = np.asarray(waveform_dataset) if preload_store else None
        energy_values = np.asarray(energy_dataset) if preload_store else None
        for start in range(0, sorted_rows.size, FEATURE_CHUNK_SIZE):
            stop = min(start + FEATURE_CHUNK_SIZE, sorted_rows.size)
            rows = sorted_rows[start:stop]
            destinations = order[start:stop]
            chunk_charge, chunk_current, fallback_count = extract_o2_features(
                waveform_values[rows]
                if waveform_values is not None
                else waveform_dataset[rows],
                energy_values[rows]
                if energy_values is not None
                else energy_dataset[rows],
            )
            charge[destinations] = chunk_charge
            current[destinations] = chunk_current
            t10_fallback_count += fallback_count
    return PartitionData(
        charge,
        current,
        labels,
        weights,
        peak_ids,
        t10_fallback_count,
    )


def standardize_features(
    train: PartitionData,
    validation: PartitionData,
) -> dict[str, float]:
    """Standardize each branch using train-only statistics."""
    statistics: dict[str, float] = {}
    for name in ("charge", "current"):
        train_values = getattr(train, name)
        mean = float(np.mean(train_values, dtype=np.float64))
        standard_deviation = float(np.std(train_values, dtype=np.float64))
        if not np.isfinite(standard_deviation) or standard_deviation <= 0.0:
            raise ValueError(f"Invalid training standard deviation for {name}")
        validation_values = getattr(validation, name)
        train_values -= mean
        train_values /= standard_deviation
        validation_values -= mean
        validation_values /= standard_deviation
        statistics[f"{name}_mean"] = mean
        statistics[f"{name}_std"] = standard_deviation
    return statistics


class ConvBranch(nn.Module):
    def __init__(self, channels: list[int], kernels: list[int], embedding_dim: int) -> None:
        super().__init__()
        layers: list[nn.Module] = []
        in_channels = 1
        for out_channels, kernel in zip(channels, kernels):
            layers.extend(
                (
                    nn.Conv1d(
                        in_channels,
                        out_channels,
                        kernel_size=kernel,
                        padding=kernel // 2,
                    ),
                    nn.BatchNorm1d(out_channels),
                    nn.GELU(),
                    nn.MaxPool1d(kernel_size=2),
                )
            )
            in_channels = out_channels
        self.convolution = nn.Sequential(*layers)
        self.embedding = nn.Sequential(
            nn.AdaptiveAvgPool1d(1),
            nn.Flatten(),
            nn.Linear(channels[-1], embedding_dim),
            nn.LayerNorm(embedding_dim),
            nn.GELU(),
        )

    def forward(self, values: Tensor) -> Tensor:
        return self.embedding(self.convolution(values))


class O2LateFusion(nn.Module):
    def __init__(self) -> None:
        super().__init__()
        self.charge_branch = ConvBranch([16, 32, 64], [9, 9, 7], 64)
        self.current_branch = ConvBranch([16, 32, 64], [7, 7, 5], 64)
        self.fusion = nn.Sequential(
            nn.Linear(128, 64),
            nn.LayerNorm(64),
            nn.GELU(),
            nn.Dropout(0.20),
            nn.Linear(64, 1),
        )

    def forward(self, charge: Tensor, current: Tensor) -> Tensor:
        charge_embedding = self.charge_branch(charge.unsqueeze(1))
        current_embedding = self.current_branch(current.unsqueeze(1))
        return self.fusion(torch.cat((charge_embedding, current_embedding), dim=1)).squeeze(1)


def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False


def metric_summary(
    labels: np.ndarray,
    scores: np.ndarray,
    weights: np.ndarray,
) -> dict[str, float]:
    return {
        "auroc": float(roc_auc_score(labels, scores)),
        "weighted_auroc": float(roc_auc_score(labels, scores, sample_weight=weights)),
        "average_precision": float(average_precision_score(labels, scores)),
        "weighted_average_precision": float(
            average_precision_score(labels, scores, sample_weight=weights)
        ),
    }


def evaluate(
    model: nn.Module,
    loader: DataLoader[tuple[Tensor, ...]],
    device: torch.device,
) -> tuple[float, dict[str, float], np.ndarray, np.ndarray]:
    model.eval()
    losses: list[float] = []
    labels: list[np.ndarray] = []
    scores: list[np.ndarray] = []
    weights: list[np.ndarray] = []
    with torch.no_grad():
        for charge, current, target, sample_weight in loader:
            charge = charge.to(device, non_blocking=True)
            current = current.to(device, non_blocking=True)
            target = target.to(device, non_blocking=True)
            sample_weight = sample_weight.to(device, non_blocking=True)
            logits = model(charge, current)
            batch_loss = nn.functional.binary_cross_entropy_with_logits(
                logits,
                target,
                reduction="none",
            )
            losses.append(float((batch_loss * sample_weight).sum().item()))
            labels.append(target.cpu().numpy())
            scores.append(torch.sigmoid(logits).cpu().numpy())
            weights.append(sample_weight.cpu().numpy())
    label_array = np.concatenate(labels)
    score_array = np.concatenate(scores)
    weight_array = np.concatenate(weights)
    total_weight = float(np.sum(weight_array))
    metrics = metric_summary(label_array, score_array, weight_array)
    return sum(losses) / total_weight, metrics, label_array, score_array


def train_epoch(
    model: nn.Module,
    loader: DataLoader[tuple[Tensor, ...]],
    optimizer: torch.optim.Optimizer,
    device: torch.device,
) -> float:
    model.train()
    weighted_loss_sum = 0.0
    weight_sum = 0.0
    for charge, current, target, sample_weight in loader:
        charge = charge.to(device, non_blocking=True)
        current = current.to(device, non_blocking=True)
        target = target.to(device, non_blocking=True)
        sample_weight = sample_weight.to(device, non_blocking=True)
        optimizer.zero_grad(set_to_none=True)
        logits = model(charge, current)
        losses = nn.functional.binary_cross_entropy_with_logits(
            logits,
            target,
            reduction="none",
        )
        loss = (losses * sample_weight).sum() / sample_weight.sum()
        loss.backward()
        optimizer.step()
        weighted_loss_sum += float((losses * sample_weight).sum().item())
        weight_sum += float(sample_weight.sum().item())
    return weighted_loss_sum / weight_sum


def make_loader(
    data: PartitionData,
    batch_size: int,
    shuffle: bool,
    seed: int,
) -> DataLoader[tuple[Tensor, ...]]:
    tensors = TensorDataset(
        torch.from_numpy(data.charge),
        torch.from_numpy(data.current),
        torch.from_numpy(data.labels),
        torch.from_numpy(data.weights),
    )
    generator = torch.Generator()
    generator.manual_seed(seed)
    return DataLoader(
        tensors,
        batch_size=batch_size,
        shuffle=shuffle,
        generator=generator,
        num_workers=0,
        pin_memory=torch.cuda.is_available(),
        drop_last=False,
    )


def per_peak_metrics(
    labels: np.ndarray,
    scores: np.ndarray,
    weights: np.ndarray,
    peak_ids: np.ndarray,
) -> dict[str, dict[str, float]]:
    result: dict[str, dict[str, float]] = {}
    for peak_id in sorted(set(peak_ids.tolist())):
        mask = peak_ids == peak_id
        result[peak_id] = metric_summary(labels[mask], scores[mask], weights[mask])
        result[peak_id]["event_count"] = int(np.count_nonzero(mask))
        result[peak_id]["positive_count"] = int(np.count_nonzero(labels[mask] == 1))
        result[peak_id]["negative_count"] = int(np.count_nonzero(labels[mask] == 0))
    return result


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--labels-dir",
        type=Path,
        default=PROJECT_ROOT / "outputs/labels",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=PROJECT_ROOT / "outputs/models/o2_late_fusion",
    )
    parser.add_argument("--epochs", type=int, default=TRAINING_CONFIG["max_epochs"])
    parser.add_argument(
        "--batch-size",
        type=int,
        default=TRAINING_CONFIG["batch_size"],
    )
    parser.add_argument("--seed", type=int, default=TRAINING_CONFIG["seed"])
    parser.add_argument(
        "--patience",
        type=int,
        default=TRAINING_CONFIG["early_stopping_patience"],
    )
    parser.add_argument(
        "--max-events-per-partition",
        type=int,
        default=None,
        help="Optional smoke-test limit; omit for the complete train/validation manifests.",
    )
    parser.add_argument(
        "--event-store-dir",
        type=Path,
        default=None,
        help="Optional consolidated event-store directory for faster waveform reads.",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Replace an existing output directory.",
    )
    return parser


def save_json(path: Path, value: Any) -> None:
    path.write_text(json.dumps(value, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def main() -> int:
    args = build_parser().parse_args()
    labels_dir = args.labels_dir.resolve()
    output_dir = args.output_dir.resolve()
    checkpoint_path = output_dir / "o2_late_fusion_best.pt"
    if output_dir.exists() and any(output_dir.iterdir()) and not args.overwrite:
        raise FileExistsError(
            f"Output directory is not empty: {output_dir}; use --overwrite to replace it"
        )
    output_dir.mkdir(parents=True, exist_ok=True)

    if args.epochs < 1 or args.batch_size < 1 or args.patience < 1:
        raise ValueError("epochs, batch-size, and patience must be positive")
    set_seed(args.seed)

    train_csv = labels_dir / "label_pairs_train.csv"
    validation_csv = labels_dir / "label_pairs_validation.csv"
    dataset_manifest = labels_dir / "label_dataset_manifest.json"
    partition_manifest = labels_dir / "file_partition_manifest.json"
    for path in (train_csv, validation_csv, dataset_manifest, partition_manifest):
        if not path.is_file():
            raise FileNotFoundError(path)

    print("Loading train features from referenced HDF5 rows ...", flush=True)
    train_data = build_partition_features(
        train_csv,
        max_events=args.max_events_per_partition,
        event_store_dir=args.event_store_dir.resolve()
        if args.event_store_dir is not None
        else None,
    )
    print("Loading validation features from referenced HDF5 rows ...", flush=True)
    validation_data = build_partition_features(
        validation_csv,
        max_events=args.max_events_per_partition,
        event_store_dir=args.event_store_dir.resolve()
        if args.event_store_dir is not None
        else None,
    )
    feature_statistics = standardize_features(train_data, validation_data)

    train_loader = make_loader(train_data, args.batch_size, True, args.seed)
    train_eval_loader = make_loader(train_data, args.batch_size, False, args.seed)
    validation_loader = make_loader(validation_data, args.batch_size, False, args.seed)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = O2LateFusion().to(device)
    optimizer = torch.optim.AdamW(
        model.parameters(),
        lr=TRAINING_CONFIG["learning_rate"],
        weight_decay=TRAINING_CONFIG["weight_decay"],
    )

    history: list[dict[str, Any]] = []
    best_metric = -np.inf
    best_epoch = -1
    epochs_without_improvement = 0
    for epoch in range(1, args.epochs + 1):
        train_loss = train_epoch(model, train_loader, optimizer, device)
        train_eval_loss, train_metrics, _, _ = evaluate(
            model,
            train_eval_loader,
            device,
        )
        validation_loss, validation_metrics, _, _ = evaluate(
            model,
            validation_loader,
            device,
        )
        epoch_metrics = {
            "epoch": epoch,
            "train_loss": train_loss,
            "train_eval_loss": train_eval_loss,
            "validation_loss": validation_loss,
            "train": train_metrics,
            "validation": validation_metrics,
        }
        history.append(epoch_metrics)
        current_metric = validation_metrics["weighted_auroc"]
        print(
            f"epoch={epoch:02d} train_loss={train_loss:.5f} "
            f"train_auroc={train_metrics['auroc']:.5f} "
            f"val_auroc={validation_metrics['auroc']:.5f} "
            f"val_weighted_auroc={current_metric:.5f}",
            flush=True,
        )
        if current_metric > best_metric + 1.0e-4:
            best_metric = current_metric
            best_epoch = epoch
            epochs_without_improvement = 0
            torch.save(
                {
                    "model_state_dict": {
                        key: value.detach().cpu()
                        for key, value in model.state_dict().items()
                    },
                    "architecture": ARCHITECTURE,
                    "feature_statistics": feature_statistics,
                    "seed": args.seed,
                    "best_epoch": best_epoch,
                },
                checkpoint_path,
            )
        else:
            epochs_without_improvement += 1
            if epochs_without_improvement >= args.patience:
                print(f"early_stop=epoch_{epoch}", flush=True)
                break

    checkpoint = torch.load(checkpoint_path, map_location=device, weights_only=False)
    model.load_state_dict(checkpoint["model_state_dict"])
    train_loss, train_metrics, train_labels, train_scores = evaluate(
        model,
        train_eval_loader,
        device,
    )
    validation_loss, validation_metrics, validation_labels, validation_scores = evaluate(
        model,
        validation_loader,
        device,
    )
    train_peak_ids = train_data.peak_ids
    validation_peak_ids = validation_data.peak_ids
    metrics = {
        "selection_metric": "validation_weighted_auroc",
        "best_epoch": best_epoch,
        "train": {
            **train_metrics,
            "loss": train_loss,
            "per_peak": per_peak_metrics(
                train_labels,
                train_scores,
                train_data.weights,
                train_peak_ids,
            ),
        },
        "validation": {
            **validation_metrics,
            "loss": validation_loss,
            "per_peak": per_peak_metrics(
                validation_labels,
                validation_scores,
                validation_data.weights,
                validation_peak_ids,
            ),
        },
    }

    run_metadata = {
        "created_utc": utc_now(),
        "model": ARCHITECTURE,
        "training": {
            **TRAINING_CONFIG,
            "epochs_requested": args.epochs,
            "patience_requested": args.patience,
            "batch_size": args.batch_size,
            "seed": args.seed,
            "device": str(device),
            "torch_version": torch.__version__,
            "cuda_device": torch.cuda.get_device_name(0)
            if torch.cuda.is_available()
            else None,
        },
        "representation": {
            "baseline_zero_based": "0:1000 median per event",
            "charge_baseline_subtraction": "baseline - raw waveform",
            "charge_smoothing": "causal moving average, width 10 samples (40 ns)",
            "t10_definition": "linearly interpolated first 10%-of-smoothed-pulse crossing in 1000:2000; non-positive smoothed peaks use deterministic t10=1000 fallback",
            "charge_window": "t10 - 250 through t10 + 499 (750 samples; -1 us/+2 us)",
            "current_definition": "np.gradient(charge, 4 ns)",
            "current_peak_search": "1100:1500",
            "current_window": "peak - 125 through peak + 125 (251 samples; +/-0.5 us)",
            "normalization": "positive shaped_energy_unit per event",
            "global_standardization": "train-only mean and standard deviation per branch",
        },
        "input": {
            "train_csv": train_csv.relative_to(PROJECT_ROOT).as_posix(),
            "validation_csv": validation_csv.relative_to(PROJECT_ROOT).as_posix(),
            "test_csv": "outputs/labels/label_pairs_test.csv",
            "test_csv_hashed": False,
            "label_dataset_manifest_sha256": sha256_file(dataset_manifest),
            "file_partition_manifest_sha256": sha256_file(partition_manifest),
            "train_csv_sha256": sha256_file(train_csv),
            "validation_csv_sha256": sha256_file(validation_csv),
            "train_event_count": int(train_data.labels.size),
            "validation_event_count": int(validation_data.labels.size),
            "t10_fallback_count": {
                "train": train_data.t10_fallback_count,
                "validation": validation_data.t10_fallback_count,
            },
            "test_partition_used": False,
            "max_events_per_partition": args.max_events_per_partition,
            "event_store_dir": args.event_store_dir.resolve().relative_to(PROJECT_ROOT).as_posix()
            if args.event_store_dir is not None
            else None,
        },
        "feature_statistics": feature_statistics,
        "metrics_file": "internal_metrics.json",
        "checkpoint_file": checkpoint_path.name,
        "caveats": [
            "Internal, file-disjoint validation AUROC on the exploratory all-valid-HDF5 manifest.",
            "Validation AUROC selected the checkpoint and is therefore model-selection biased.",
            "Positive and negative classes originate from different isotope sources; source/session/QC shortcuts may inflate AUROC.",
            "The exploratory manifest retains WARN/FAIL/UNKNOWN QC provenance; this is not a QC-locked physics result.",
            "The test partition was not loaded or evaluated; its CSV is deliberately not opened or hashed.",
        ],
    }
    save_json(output_dir / "internal_metrics.json", metrics)
    save_json(output_dir / "training_run.json", run_metadata)
    save_json(output_dir / "training_history.json", {"history": history})

    print(
        json.dumps(
            {
                "output_dir": output_dir.relative_to(PROJECT_ROOT).as_posix(),
                "checkpoint": checkpoint_path.relative_to(PROJECT_ROOT).as_posix(),
                "best_epoch": best_epoch,
                "internal_train_auroc": metrics["train"]["auroc"],
                "internal_validation_auroc": metrics["validation"]["auroc"],
                "internal_validation_weighted_auroc": metrics["validation"][
                    "weighted_auroc"
                ],
                "internal_validation_average_precision": metrics["validation"][
                    "average_precision"
                ],
                "test_partition_used": False,
            },
            indent=2,
            sort_keys=True,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
